# Generated by Django 4.1.3 on 2022-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_alter_skill_category_alter_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
