# Generated by Django 4.1.3 on 2022-11-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_experience_delete_blog_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='time_range',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
